version: '3.6'
services:
  mqttheat:
    build: 
      context: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yml:/config.yml
#    environment:
#      - LOGLEVEL=DEBUG